# Generated by Django 3.2.15 on 2022-08-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_class',
            field=models.CharField(max_length=100),
        ),
    ]
