# Generated by Django 3.2.15 on 2022-08-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialog_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InteractionML',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
